### PR TITLE
dependency bumps

### PR DESCRIPTION
**Pull request by larsrh**

### CODE REVIEW

**Comment by larsrh** [comment]
Blocked on scoverage/sbt-scoverage#295

**Comment by larsrh** [comment]
This still doesn't work, but I have no idea why.

**Comment by fthomas** [comment]
I think you need to bump sbt-mdoc to 1.3.6: https://github.com/scalameta/mdoc/releases/tag/v1.3.6

**Comment by larsrh** [comment]
Thanks, that did the trick!

**Pull request merged**
