### PR TITLE
Added monad chronicle syntax tests

### PR DESCRIPTION
**Pull request by YuvalItzchakov**
Missing syntax tests from `MonadChronicle` implementation.

### CODE REVIEW

**Comment by kailuowang** [comment]
I think we need to contact GitHub why your PR doesn't trigger webhook. Do your other PRs at other repos work?

**Comment by YuvalItzchakov** [comment]
Yes, haven't had any problems up to now. I'll try and contact them.

**Comment by YuvalItzchakov** [comment]
@kailuowang I contacted GitHub, still no reply (been like a week already) :(. Is there anyway perhaps to look at Travis logs or the likes? Or is this purely a GitHub thing not triggering Travis at all?

**Comment by kailuowang** [comment]
There is nothing on travis, it's like the PR doesn't exist to travis at all. And not much I can see from the github side either.

**Pull request merged**
